#!/bin/bash
# aliases

alias termpv='mpv -vo=tct "$1" --really-quiet=yes'
alias e='nvim'
alias c='clear'
alias q='exit'
alias cr='clear; reset'
alias gpp='g++'
alias venv='source /opt/miniconda3/etc/profile.d/conda.sh'
alias duf='duf -hide-fs tmpfs'

openports(){
	doas lsof -i -P -n | grep LISTEN
}

# lists orphan packages
list-orphan(){
	pacman -Qdt
}

# removes orphan packages
remove-orphan(){
	doas pacman -Rsn $(pacman -Qdtq)
}

# download youtube video id's thumb
ythumb(){
	if wget "https://i.ytimg.com/vi/$1/maxresdefault.jpg" -O "$1.jpg"; then
		echo "Thumbnail saved as ${video_id}.jpg"
	else
		echo "Thumbnail not found."
	fi
}

# download using a https proxy. $1 is proxy, $2 url, $3 is file
dlprox(){
	if [[ -e $3 ]]; then
		wget -e https_proxy="$1" -e use_proxy=on "$2" -c -O "$3"
	else
		wget -e https_proxy="$1" -e use_proxy=on "$2" -O "$3"
	fi
}

rdl() {
	local max_tries=10
	local try=0

	while true; do
		yt-dlp \
			-o "%(uploader)s-%(title)s [%(id)s].%(ext)s" \
			--continue \
			"$@"

		if [[ $? -eq 0 ]]; then
			return 0
		fi

		((try++))
		if (( try >= max_tries )); then
			echo "Download failed after $max_tries attempts." >&2
			return 1
		fi

		echo "Download failed. Retrying in 5 seconds... ($try/$max_tries)" >&2
		sleep 5
	done
}

rproxdl() {
	local max_tries=10
	local try=0

	while true; do
		yt-dlp \
			--proxy "http://127.0.0.1:18080" \
			-o "%(uploader)s-%(title)s [%(id)s].%(ext)s" \
			--continue \
			"$@"

		if [[ $? -eq 0 ]]; then
			return 0
		fi

		((try++))
		if (( try >= max_tries )); then
			echo "Download failed after $max_tries attempts." >&2
			return 1
		fi

		echo "Download failed. Retrying in 5 seconds... ($try/$max_tries)" >&2
		sleep 5
	done
}

# finds $2 in file $1, replaces with $3. $1 is docx file
docx-replace(){
	FILE=$1
	FIND=$2
	REPLACE=$3
	unzip $FILE -d tmp #unzip
	sed -i -e "s/${FIND}/${REPLACE}/g" tmp/word/document.xml #find/replace
	cd tmp && zip -r "../$FILE" * && cd .. #zip
	rm -rf tmp
}

# re-encodes a PDF. $1 is input, $2 is output
reenc-pdf(){
	gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite "-sOutputFile=$2" "$1"
}

# sets newline character as terminator
endl-as-end(){
	IFS=$'\n'; set -f
}

# sets space character as terminator
space-as-end(){
	unset IFS; set +f
}

# to extract AAC audio from a MP4
extract-audio(){
	ffmpeg -i "$1" -vn -c:a copy "$2"
}

# makes a lst image sequence file. $1 is FPS, all other are image files in sequence
# output file is written to stdout
make-lst-seq(){
	echo "FPS $1"
	i=2
	while [ "$i" -le "$#" ]; do
		eval "arg=\${$i}"
		echo "$arg"
		i=$(( i + 1 ))
	done
}

# makes a "presentation video" from images and a background audio
# $1 is filename pattern for images, $2 is images count,
# $3 is audio file (m4a tested), and $4 is output filename
make-vid(){
	# get audio length
	length=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$3")
	# remove fractal part
	length=$(bc <<< "$length/1")
	# calculate framerate
	framerate=$(bc <<< "$length/$2")
	# now call ffmpeg
	ffmpeg -framerate "1/$framerate" -y -i "$1" -i "$3" -c:a aac -vcodec libx264 "$4"
}

# to change extenstion of lots of files in cd
change-ext(){
	for f in *.$1; do
		[ -f "$f" ] && mv -v "$f" "${f%$1}$2"
		echo "$f -> ${f%$1}$2"
	done
}

# extracts links from page, where $1 is file, and $2 is the tag-addribute containing link
extract-links(){
	grep -Po '(?<='"$2"'=")[^"]*' "$1"
}

# renames all files to numbers, where $1 is formatting for the number
rename-files(){
	a=1
	for i in *; do
	  new=$(printf "$1.${i##*.}" "$a") #04 pad to length of 4
	  mv -i -- "$i" "$new"
	  let a=a+1
	done
}
