#!/bin/bash
[[ $- != *i* ]] && return
[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}  ${PWD/#$HOME/\~}\007"'

PS1='\[\e[1;30;44m\] \u \[\e[0;34;104m\]\[\e[1;30;104m\] \h \[\e[0;94;42m\]\[\e[0;30;42m\] \W \[\e[0;32m\]\[\e[0m\] '

alias ls='ls --color=auto'
alias grep='grep --colour=auto'

alias cp="cp -i" # confirm before overwriting something

#xhost +local:root > /dev/null 2>&1

complete -cf doas
shopt -s checkwinsize
shopt -s expand_aliases
shopt -s histappend
# disable job control (that Ctrl+Z thing)
set +m

export HISTCONTROL=ignoreboth:erasedups
if [ -f ~/.bash_aliases ]; then
	.	~/.bash_aliases
fi
export STEAM_FRAME_FORCE_CLOSE=1
export PATH=$PATH:$HOME/.local/bin:$HOME/.dotnet/tools
export EDITOR=nvim
export LIBVIRT_DEFAULT_URI="qemu:///system"
export QT_QPA_PLATFORMTHEME="qt6ct"
export GPG_TTY=$(tty)
export _JAVA_AWT_WM_NONREPARENTING=1
#export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'

export CHROME_EXECUTABLE=/usr/bin/chromium
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1

export WINEPREFIX=~/.wineprefixes/default
