#!/bin/bash
[[ $- != *i* ]] && return
[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

parse_git_branch() {
	git branch --show-current 2>/dev/null
}
update_ps1() {
	local exit_code=$?
	local reset='\[\e[0m\]'
	local blue='\[\e[34m\]'
	local green='\[\e[32m\]'
	local red='\[\e[31m\]'
	local gray='\[\e[90m\]'
	local cwd="${blue}\w${reset}"
	local git_branch
	git_branch=$(parse_git_branch)
	if [[ -n "$git_branch" ]]; then
		git_branch=" ${green}[$git_branch]${reset}"
	fi
	local status=""
	if [[ $exit_code -ne 0 ]]; then
		status=" ${red}(exit: $exit_code)${reset}"
	fi
	PS1="${cwd}${git_branch}${status}\n${gray}> ${reset}"
}
PROMPT_COMMAND=update_ps1

alias ls='ls --color=auto'
alias grep='grep --colour=auto'

alias cp="cp -i" # confirm before overwriting something

complete -cf doas
shopt -s checkwinsize
shopt -s expand_aliases
shopt -s histappend
shopt -s globstar
# disable job control (that Ctrl+Z thing)
set +m

export HISTCONTROL=ignoreboth:erasedups

export STEAM_FRAME_FORCE_CLOSE=1
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export PATH=$PATH:$HOME/.local/bin:$HOME/.dotnet/tools
export EDITOR=nvim
export LIBVIRT_DEFAULT_URI="qemu:///system"
export QT_QPA_PLATFORMTHEME="qt6ct"
export GPG_TTY=$(tty)
export _JAVA_AWT_WM_NONREPARENTING=1
export ELECTRON_OZONE_PLATFORM_HINT=wayland
#export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
export WINEPREFIX="$HOME/.wineprefixes/default"

if [ -f ~/.bash_aliases ]; then
	.	~/.bash_aliases
fi
